### ISSUE TITLE
Add support /dev/fuse

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#21] opened 2016-02-29 13:18 UTC
Hi,

Please possible add support fuse module ?

Thank you

**Comment by ailispaw** [comment] 2016-02-29 13:20
Hi @cedvan ,
Thank you for opening an issue.

How can I add that module and test it?
Could you make a PR for it?

**Comment by cedvan** [comment] 2016-02-29 13:23
I don't know, but I can try

**Comment by ailispaw** [comment] 2016-02-29 13:30
If all you need is fuse in user land, you can install with https://github.com/ailispaw/docker-root-pkg.

```
$ sudo pkg install libfuse
```

It will install `/usr/bin/fusermount` and `/usr/lib/libfuse.so*`.

If you need any kernel configuration for it, please let me know.

**Comment by ailispaw** [comment] 2016-02-29 13:36
May need `CONFIG_FUSE_FS` in `kernel.config`, too.

**Comment by ailispaw** [comment] 2016-02-29 13:38
https://github.com/libfuse/libfuse

**Comment by cedvan** [comment] 2016-02-29 13:52
Thank you !

I had install fuse with `sudo pkg install libfuse`.

Result : 

```
$ modprobe -l |grep fuse
kernel/drivers/message/fusion/mptbase.ko
kernel/drivers/message/fusion/mptscsih.ko
kernel/drivers/message/fusion/mptspi.ko
kernel/drivers/message/fusion/mptsas.ko
kernel/drivers/message/fusion/mptctl.ko
$ cat /dev/fuse
cat: can't open '/dev/fuse': No such file or directory
```

Need `CONFIG_FUSE_FS` to enable fuse ?
Where is `kernel.config` file please ?

**Comment by ailispaw** [comment] 2016-02-29 13:55
https://github.com/ailispaw/docker-root/blob/master/configs/kernel.config#L2028

**Comment by ailispaw** [comment] 2016-02-29 13:58
`sudo pkg install libfuse` installs only modules in userspace.
You need `CONFIG_FUSE_FS` for kernel modules and devices.

**Comment by ailispaw** [comment] 2016-02-29 13:59
``` diff
diff --git a/configs/buildroot.config b/configs/buildroot.config
index 2a62e5c..571277b 100644
--- a/configs/buildroot.config
+++ b/configs/buildroot.config
@@ -1065,7 +1065,7 @@ BR2_PACKAGE_OPENSSL=y
 # BR2_PACKAGE_GAMIN is not set
 # BR2_PACKAGE_LIBCONFIG is not set
 # BR2_PACKAGE_LIBCONFUSE is not set
-# BR2_PACKAGE_LIBFUSE is not set
+BR2_PACKAGE_LIBFUSE=y
 # BR2_PACKAGE_LIBLOCKFILE is not set
 # BR2_PACKAGE_LIBNFS is not set
 # BR2_PACKAGE_LIBSYSFS is not set
diff --git a/configs/kernel.config b/configs/kernel.config
index 2fad792..602e5dc 100644
--- a/configs/kernel.config
+++ b/configs/kernel.config
@@ -2025,7 +2025,8 @@ CONFIG_INOTIFY_USER=y
 # CONFIG_QUOTA is not set
 # CONFIG_QUOTACTL is not set
 # CONFIG_AUTOFS4_FS is not set
-# CONFIG_FUSE_FS is not set
+CONFIG_FUSE_FS=y
+# CONFIG_CUSE is not set
 CONFIG_OVERLAY_FS=y

 #
```

**Comment by cedvan** [comment] 2016-02-29 14:02
Ok thank you very much !

I will create a PR as soon as possible ;)

**Comment by ailispaw** [comment] 2016-02-29 14:04
If that modification doesn't make kernel bigger significantly, I will add `CONFIG_FUSE_FS` in the next release.

**Comment by ailispaw** [comment] 2016-02-29 14:06
BTW, what fuse will benefit and what is your use case?

**Comment by cedvan** [comment] 2016-02-29 14:50
I need fuse to support glusterfs :)

**Comment by ailispaw** [comment] 2016-02-29 15:00
Is glusterfs in a container or VM?
I'm very interested in that.

**Comment by ailispaw** [comment] 2016-02-29 15:01
Oh it seems silly question.. forget it. :)

**Comment by ailispaw** [comment] 2016-02-29 15:02
Please provide how to use it with the PR.

**Comment by ailispaw** [comment] 2016-02-29 15:04
Are you trying to use GlusterFS from a container or in DockerRoot VM?

**Comment by cedvan** [comment] 2016-02-29 15:10
I create 2 DockerRoot VM hosting container GlusterFS Server. And I create 2 DockerRoot VM hosting container GlusterFS Convoy Docker (Client). Convoy need fuse in kernel to share data with server

**Comment by ailispaw** [comment] 2016-02-29 15:14
I see. Thanks. So it seems you need just `CONFIG_FUSE_FS` in kernel.config.

**Comment by cedvan** [comment] 2016-02-29 15:18
Ok, I have to create a PR, or you do it ?

**Comment by ailispaw** [comment] 2016-02-29 15:21
I can do it, but can not test it with GlusterFS. Please make and test it in your side.
I'm looking forward to reading your instruction about GlusterFS with DockerRoot.

**Comment by cedvan** [comment] 2016-02-29 15:27
Ok, tell me when I can test, and I'll make a return ;)

**Comment by ailispaw** [comment] 2016-02-29 15:28
Do you need docker-root.iso or docker-root.box?
I will make it for you.

**Comment by cedvan** [comment] 2016-02-29 15:29
I use Vagrant, so need docker-root.box please.
Thank you !

**Comment by ailispaw** [comment] 2016-02-29 15:30
OK.

**Comment by ailispaw** [comment] 2016-02-29 15:57
https://gist.github.com/ailispaw/ec0ebf417ca66283e0de

**Comment by ailispaw** [comment] 2016-02-29 16:01
Please download `docker-root.box` from `RAW` link at the gist. Or just `git clone` the gist.

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "docker-root-fuse"
  config.vm.box_url = "docker-root.box"
end
```

``` bash
$ vagrant up
$ vagrant ssh -c "ls -l /dev/fuse"
crw-------    1 root     root       10, 229 Feb 29 15:59 /dev/fuse
```

**Comment by ailispaw** [comment] 2016-02-29 16:04
Now it's 1 am in Japan. Going to bed. @cedvan See you tomorrow.

**Comment by cedvan** [comment] 2016-02-29 16:07
Thank you ! 

I am in France, I test tonight ;) 

Good night man !

**Comment by cedvan** [comment] 2016-03-02 15:54
Hi,

I've test. I've other problems to start glusterfs, but /dev/fuse problem is fixed :)

Thank you very much !

**Comment by ailispaw** [comment] 2016-03-02 16:01
@cedvan Thank you for testing.
Is only `CONFIG_FUSE_FS` enough for you to use glusterfs with DockerRoot?

**Comment by cedvan** [comment] 2016-03-02 16:02
For now , I will return to you if necessary ;)

**Comment by ailispaw** [comment] 2016-03-02 16:04
OK, I will wait for your response to merge it.

**Comment by ailispaw** [comment] 2016-03-04 14:20
@cedvan Are you still testing?
I would like to merge it, if your test is completed successfully.

**Comment by cedvan** [comment] 2016-03-06 00:17
hi,

I had test your box with fuse. First problem is solved, thank you ! 

New error now :

```
6/3/2016 01:12:40Waiting for metadata.
6/3/2016 01:12:40time="2016-03-06T00:12:40Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/241/ns/mnt -F -- /mnt/sda1/var/lib/docker/overlay/1f2eee3b0e79b3718cec74e0d3938a25615d8db8eaede240a139cea4244f5928/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/gluster-convoy-761687de-4ff5-4677-9ce5-d97119df71ac -- /launch volume-agent-glusterfs-internal]"
6/3/2016 01:12:40Timestamp: 2016-03-06 00:12:40.995514645 +0000 UTC
6/3/2016 01:12:40Code: System error
6/3/2016 01:12:40
6/3/2016 01:12:40Message: pivot_root invalid argument
6/3/2016 01:12:40
6/3/2016 01:12:40Frames:
6/3/2016 01:12:40---
6/3/2016 01:12:400: setupRootfs
6/3/2016 01:12:40Package: github.com/opencontainers/runc/libcontainer
6/3/2016 01:12:40File: rootfs_linux.go@69
6/3/2016 01:12:40---
6/3/2016 01:12:401: Init
6/3/2016 01:12:40Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
6/3/2016 01:12:40File: standard_init_linux.go@57
6/3/2016 01:12:40---
6/3/2016 01:12:402: StartInitialization
6/3/2016 01:12:40Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
6/3/2016 01:12:40File: factory_linux.go@242
6/3/2016 01:12:40---
6/3/2016 01:12:403: init·1
6/3/2016 01:12:40Package: main
6/3/2016 01:12:40File: start.go@71
6/3/2016 01:12:40---
6/3/2016 01:12:404: init
6/3/2016 01:12:40Package: main
6/3/2016 01:12:40File: utils.go@177
6/3/2016 01:12:40---
6/3/2016 01:12:405: main
6/3/2016 01:12:40Package: runtime
6/3/2016 01:12:40File: proc.go@58
6/3/2016 01:12:40---
6/3/2016 01:12:41time="2016-03-06T00:12:41Z" level=warning msg="signal: killed"
6/3/2016 01:12:41time="2016-03-06T00:12:41Z" level=error msg="Failed to start (pid 5467) &libcontainer.Process{Args:[]string{\"/launch\", \"volume-agent-glusterfs-internal\"}, Env:[]string{\"CATTLE_CONFIG_URL=https://infra.cedvan.com/v1\", \"HOSTNAME=1f2eee3b0e79\", \"CATTLE_ACCESS_KEY=67D66DFB7166DF758422\", \"CATTLE_AGENT_INSTANCE_AUTH=Basic NjdENjZERkI3MTY2REY3NTg0MjI6NDMySjFweURHbkNBY0FDckttNDJUQlh5NFc5QWNLQWtvVWo4WEdHRg==\", \"CATTLE_SECRET_KEY=432J1pyDGnCAcACrKm42TBXy4W9AcKAkoUj8XGGF\", \"PATH=/var/lib/rancher/convoy-agent:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"PWD=/\", \"SHLVL=1\", \"HOME=/root\", \"CATTLE_URL=https://infra.cedvan.com/v1\", \"_=/var/lib/rancher/convoy-agent/share-mnt\"}, User:\"0:0\", Cwd:\"\", Stdin:(*os.File)(0xc208050028), Stdout:(*os.File)(0xc2080500a0), Stderr:(*os.File)(0xc2080500b0), ExtraFiles:[]*os.File(nil), consolePath:\"\", Capabilities:[]string(nil), ops:libcontainer.processOperations(nil)}: [8] System error: pivot_root invalid argument"
6/3/2016 01:12:41time="2016-03-06T00:12:41Z" level=fatal msg="[8] System error: pivot_root invalid argument"
6/3/2016 01:12:416: goexit
```

An idea ?

**Comment by ailispaw** [comment] 2016-03-06 00:24
What is this an output of?
Could you provide your Vagrantfile and environment?

**Comment by cedvan** [comment] 2016-03-06 00:49
Output is logs of `gluster-convoy` from rancher server.

I launch VMs on Ubuntu server 14.04.

My Vagrantfile : 

```
$number_of_nodes = 3
$vm_cpus = 2
$vm_mem = 4096
$vm_gui = false

Vagrant.configure(2) do |config|

  config.vm.box = "ailispaw/docker-root-fuse"
  config.vm.box_url = "docker-root.box"

  (1..$number_of_nodes).each do |i|
    hostname = "rancher-node-%d" % i

    config.vm.define hostname do |node|

        node.vm.hostname = hostname

        node.vm.provider "virtualbox" do |vb|
        vb.cpus = $vm_cpus
            vb.memory = $vm_mem
            vb.gui = $vm_gui
        end

        ip = "192.168.1.2#{i}"
        node.vm.network "public_network", ip: ip, bridge: "eth0"

        node.vm.provision "shell",
        inline: "echo nameserver 192.168.1.2 > /etc/resolv.conf"

        node.vm.provision "shell",
            inline: "echo nameserver 8.8.8.8 >> /etc/resolv.conf"

        # Enable IPVS
        node.vm.provision "shell",
            inline: "sudo modprobe -a ip_vs.ko"

        # Data rancher
        node.vm.synced_folder "/data/nodes/node#{i}", "/var/lib/rancher", disabled: false

        node.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end
end
```

**Comment by ailispaw** [comment] 2016-03-06 01:02
Thanks. I will try it.

What is `/var/lib/rancher` for?
Any other provisions to the VMs for gluster-convoy and/or rancher server? I'm not familiar with them though.

**Comment by cedvan** [comment] 2016-03-06 01:12
`/var/lib/rancher` is use by `rancher-agent` to save VM state (containers informations, etc...). I mount this folder to preserve informations when reboot VM.

The provisioning depends on the services that we want to start on the VM.

Examples :
- `ipvs` to keepalived
- `fuse` to glusterfs, maybe other ?

**Comment by cedvan** [comment] 2016-03-06 01:19
I need glusterfs because nfs and vboxsf are not sufficient. My server provide a raid 6 storage. I want use him to save docker volumes is my VMs. With nfs or vboxsf, I've problem with permissions, some containers need to change ownership on volume. I hope that glusterfs will allow...

**Comment by cedvan** [comment] 2016-03-06 01:26
At the beginning I wanted to use Rancher OS, but a lot of network problems with vagrant because the docker system. Your box allowed me to get a VM light and clean (network, hostname, dns) to launch my containers. It's great !

Now, only one last missing, the management of the storage volumes. Glusterfs may be the solution ?

**Comment by ailispaw** [comment] 2016-03-06 01:27
I see about the problem, but I don't understand your system yet.
Could you make a simplified whole example Vagrantfile to use glusterfs for me without others like rancher?

**Comment by ailispaw** [comment] 2016-03-06 01:28
> Now, only one last missing, the management of the storage volumes. Glusterfs may be the solution ?

I'm considering virtfs (9p). #15 , #20

**Comment by ailispaw** [comment] 2016-03-06 01:29
I have to go. See you later.

**Comment by cedvan** [comment] 2016-03-06 01:31
I'll analyze virtfs, thank you !

See you later ;)

**Comment by ailispaw** [comment] 2016-03-07 13:00
FYI: MariaDB container seems to need 9p2000.L, because it uses fstatvfs().

**Comment by cedvan** [comment] 2016-03-07 13:10
Yes, that's why I think I need glusterfs :).

**Comment by cedvan** [comment] 2016-03-07 13:11
Possible install glusterfs directly on the VM docker-root ?

**Comment by ailispaw** [comment] 2016-03-07 13:17
You can use https://github.com/ailispaw/docker-root-pkg/tree/master/extra/package as an extra package like criu and ipvsadm.

**Comment by cedvan** [comment] 2016-03-07 13:19
I am afraid of not being competent enough to succeed, but I will try

**Comment by ailispaw** [comment] 2016-03-07 13:21
FYI: I have activated SSHFS/FUSE in DockerRoot v1.3.1 as well, although I haven't tested it yet.

``` bash
$ sudo pkg install sshfs
```

**Comment by cedvan** [comment] 2016-03-07 13:23
Ok, cool. Thank you !

**Comment by cedvan** [comment] 2016-03-07 13:25
You have informations to the previous error : `pivot_root` ?

**Comment by ailispaw** [comment] 2016-03-07 13:28
Hmm. DockerRoot doesn't allow `pivot_root` by default.
It needs to re-build the  box with a patched boot config.

**Comment by cedvan** [comment] 2016-03-07 13:37
Ok, so not possible ? 

For information, what is a `pivot_root` ?

**Comment by ailispaw** [comment] 2016-03-07 13:41
like chroot. http://man7.org/linux/man-pages/man2/pivot_root.2.html

**Comment by cedvan** [comment] 2016-03-07 13:43
Hum ok ! :)

So not possible add chroot in docker-root ?

**Comment by ailispaw** [comment] 2016-03-07 13:46
> Ok, so not possible ?

I'm not sure that it is caused by DockerRoot or something else (libcontainer).
But I will create a custom box for you.

**Comment by cedvan** [comment] 2016-03-07 13:52
Oh great !

Thank you very much !!

**Comment by ailispaw** [comment] 2016-03-07 14:13
@cedvan Updated the gist with the custom docker-root.box.
https://github.com/ailispaw/docker-root/issues/21#issuecomment-190267732

**Comment by cedvan** [comment] 2016-03-07 14:19
Ok great ! I'll try ;)

**Comment by cedvan** [comment] 2016-03-07 23:29
Your box solved problem with `pivot_root`, it's very good ! 

But docker version 1.9.1 create bug with new rancher network... lol. Need merge your work on master and up to docker 1.10 ^^. I try build localy docker-root, but I've Linux, so difficult :)

**Comment by ailispaw** [comment] 2016-03-07 23:37
Thanks for your feedback. I will consider to support `pivot_root` and Docker v1.10 in the next. :)

**Comment by cedvan** [comment] 2016-03-07 23:38
Great !

**Comment by ailispaw** [comment] 2016-03-08 00:01
> Possible install glusterfs directly on the VM docker-root ?

Please open an issue at https://github.com/ailispaw/docker-root-pkg.
Thanks.

**Comment by ailispaw** [comment] 2016-03-10 22:49
I'm still wondering Docker v1.10.3 is good.

Instead I have added an ability to switch between Docker versions easily.
https://github.com/ailispaw/docker-root/commit/39acf9513be760e55cf68e0b6dde34e48c76a240

```
$ sudo /etc/init.d/docker restart v1.10.3
```

**Comment by cedvan** [comment] 2016-03-11 09:26
> I'm still wondering Docker v1.10.3 is good.

Why ?

> Instead I have added an ability to switch between Docker versions easily.

Good idea !

**Comment by ailispaw** [comment] 2016-03-11 09:29
I will try to use the latest Docker.

Please see https://github.com/ailispaw/docker-root#features for its usage.

**Comment by ailispaw** [comment] 2016-03-11 09:33
Telling the truth, I don't like the FAT docker binary and I feel it's unstable recently, although I do like its basic functionalities.

**Comment by cedvan** [comment] 2016-03-11 09:34
Ok, you do a great job, thank you !

**Comment by ailispaw** [comment] 2016-03-11 09:36
@cedvan Thank YOU. I have enjoyed this conversation with you. Without it, I could not have such ideas.

Please let me know any problem and progress on your test.

**Comment by cedvan** [comment] 2016-03-16 17:30
@ailispaw, To continue my test I need IPSec support :wink: . 

cf #27

**Comment by ailispaw** [comment] 2016-03-20 04:49
Closing for /dev/fuse.
Please open a new issue for the further problem.

**Closed as completed by ailispaw** 2016-03-20 04:49 UTC
Labels: enhancement
