### ISSUE TITLE
Add support IPSec

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#27] opened 2016-03-16 17:29 UTC
Hi,

Possible add support to IPSec please ?

Thank you

**Comment by ailispaw** [comment] 2016-03-17 00:00
Could you tell me what it needs to support IPSec?

**Comment by cedvan** [comment] 2016-03-17 15:48
I don't know.

This is my error :

```
Mar 17 15:46:19 00[DMN] Starting IKE charon daemon (strongSwan 5.3.5, Linux 4.4.5-docker-root, x86_64)
Mar 17 15:46:19 00[KNL] unable to create netlink socket
Mar 17 15:46:19 00[NET] installing IKE bypass policy failed
Mar 17 15:46:19 00[NET] installing IKE bypass policy failed
Mar 17 15:46:19 00[NET] enabling UDP decapsulation for IPv6 on port 4500 failed
Mar 17 15:46:19 00[NET] installing IKE bypass policy failed
Mar 17 15:46:19 00[NET] installing IKE bypass policy failed
Mar 17 15:46:19 00[NET] enabling UDP decapsulation for IPv4 on port 4500 failed
Mar 17 15:46:19 00[LIB] feature CUSTOM:libcharon in critical plugin 'charon' has unmet dependency: CUSTOM:kernel-ipsec
Mar 17 15:46:19 00[CFG] loading ca certificates from '/usr/local/etc/ipsec.d/cacerts'
Mar 17 15:46:19 00[LIB] opening directory '/usr/local/etc/ipsec.d/cacerts' failed: No such file or directory
Mar 17 15:46:19 00[CFG]   reading directory failed
Mar 17 15:46:19 00[CFG] loading aa certificates from '/usr/local/etc/ipsec.d/aacerts'
Mar 17 15:46:19 00[LIB] opening directory '/usr/local/etc/ipsec.d/aacerts' failed: No such file or directory
Mar 17 15:46:19 00[CFG]   reading directory failed
Mar 17 15:46:19 00[CFG] loading ocsp signer certificates from '/usr/local/etc/ipsec.d/ocspcerts'
Mar 17 15:46:19 00[LIB] opening directory '/usr/local/etc/ipsec.d/ocspcerts' failed: No such file or directory
Mar 17 15:46:19 00[CFG]   reading directory failed
Mar 17 15:46:19 00[CFG] loading attribute certificates from '/usr/local/etc/ipsec.d/acerts'
Mar 17 15:46:19 00[LIB] opening directory '/usr/local/etc/ipsec.d/acerts' failed: No such file or directory
Mar 17 15:46:19 00[CFG]   reading directory failed
Mar 17 15:46:19 00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
Mar 17 15:46:19 00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory
Mar 17 15:46:19 00[CFG]   reading directory failed
Mar 17 15:46:19 00[CFG] loading secrets from '/usr/local/etc/ipsec.secrets'
Mar 17 15:46:19 00[CFG] opening secrets file '/usr/local/etc/ipsec.secrets' failed: No such file or directory
Mar 17 15:46:19 00[LIB] failed to load 1 critical plugin feature
Mar 17 15:46:19 00[DMN] initialization failed - aborting charon
```

**Comment by ailispaw** [comment] 2016-03-18 02:18
@cedvan 
Could you tell me how I can reproduce your error?

**Comment by ailispaw** [comment] 2016-03-18 03:04
MEMO:
https://wiki.strongswan.org/projects/strongswan/wiki/KernelModules
http://www.ipsec-howto.org/x304.html
http://lartc.org/howto/lartc.ipsec.html

**Comment by cedvan** [comment] 2016-03-18 12:48
@ailispaw,

I use rancher server to launch containers on docker-root VMs. Rancher launch an agent container on each hosts to manage network communication with server. Rancher agent can't works because loading plugin libcharon failed. Libcharon has unmet dependency: CUSTOM:kernel-ipsec

Cf issue : https://github.com/rancher/rancher/issues/3668#issuecomment-194187722

**Comment by cedvan** [comment] 2016-03-18 12:51
It's strange, I believe it worked fine before, but I'm not sure.
Have you changed something ?

**Comment by ailispaw** [comment] 2016-03-18 12:56
@cedvan What version of DockerRoot do you use?

**Comment by ailispaw** [comment] 2016-03-18 12:58
If you want to use older version, you can specify a version with `config.vm.box_version = "1.3.3" in Vagrantfile.

**Comment by cedvan** [comment] 2016-03-18 13:03
Yes, I've come up till version 1.2.6 for testing. but without success.

**Comment by cedvan** [comment] 2016-03-18 13:06
IPSec is include in linux kernel since v2.6, no ? docker-root use linux kernel v4.4.6, it should support IPSec no ?

**Comment by ailispaw** [comment] 2016-03-18 13:12
I have researched a bit about IPSec.
The current DockerRoot has been missing some configurations for IPsec.
I created a commit for it, but I'm not sure it is good enough or not, because I can not test it on my side.
Please provide your test environment for me.

**Comment by cedvan** [comment] 2016-03-18 15:07
Ok :smiley:

I have a server (ip 192.168.1.10) with Ubuntu server 14.04 and docker v10.1.
I have DNS Server with bind on Raspberry PI (ip 192.168.1.2)

DNS registered :
- server.cedvan.com : 192.168.1.10
- infra.cedvan.com : 192.168.1.10

I run on my server rancher-server with :

```
docker run \
    -d \
    --restart=always \
    --name nginx-proxy \
    -p 80:80 \
    -p 443:443 \
    -e DEFAULT_HOST=server.cedvan.com \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
        -v /data/infra/data/nginx-proxy/certs:/etc/nginx/certs:ro \
    jwilder/nginx-proxy

docker run \
    -d \
    --restart=always \
    --name rancher-server \
    -e "VIRTUAL_HOST=infra.cedvan.com" \
    -e "VIRTUAL_PORT=8080" \
    -e "VIRTUAL_PROTO=http" \
        -p 500:500/udp \
        -p 4500:4500/udp \
    -v /data/infra/data/rancher-server/mysql:/var/lib/mysql \
    rancher/server:v0.59.1
```

I run on my server also 3 VMs docker-root v1.3.3 with : 

```
$number_of_nodes = 3
$vm_cpus = 2
$vm_mem = 4096
$vm_gui = false

Vagrant.configure(2) do |config|

  config.vm.box = "ailispaw/docker-root"
  config.vm.box_version = "= 1.3.3"

  (1..$number_of_nodes).each do |i|
    hostname = "rancher-node-%d" % i

    config.vm.define hostname do |node|

        node.vm.provider "virtualbox" do |vb|
        vb.cpus = $vm_cpus
            vb.memory = $vm_mem
            vb.gui = $vm_gui
        end

        ip = "192.168.1.2#{i}"
        node.vm.network "public_network", ip: ip, bridge: "eth0"

        node.vm.hostname = hostname

        # Enable IPVS
        node.vm.provision "shell",
            inline: "sudo modprobe -a ip_vs.ko"

        node.vm.provision "shell",
        inline: "echo nameserver 192.168.1.2 > /etc/resolv.conf"

        node.vm.provision "shell",
            inline: "echo nameserver 8.8.8.8 >> /etc/resolv.conf"

        node.vm.synced_folder ".", "/vagrant", disabled: true

    end
  end
end
```

Next, connect to `infra.cedvan.com` and add VM as custom host :
![add-host](https://cloud.githubusercontent.com/assets/4289595/13879061/a9d822d0-ed15-11e5-9cca-17365d74f574.png)

```
ubuntu$ vagrant ssh rancher-node-1
rancher-node-1$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.9.2 https://infra.cedvan.com/v1/scripts/FE28F235CD13B4E36E23:1458306000000:geVAXcqhCW0hoZKiHXBat7JpbvQ
Unable to find image 'rancher/agent:v0.9.2' locally
v0.9.2: Pulling from rancher/agent
92ec6d044cb3: Pull complete 
2ef91804894a: Pull complete 
f80999a1f330: Pull complete 
6cc0fc2a5ee3: Pull complete 
697c9d107a67: Pull complete 
a0e5624395d1: Pull complete 
e25352db59ac: Pull complete 
dc6d7e7ca6f0: Pull complete 
415916094fe4: Pull complete 
6c4c7e696ae9: Pull complete 
51211b838e06: Pull complete 
53964e957557: Pull complete 
ed8efa7e2e3e: Pull complete 
4e2ef5b85846: Pull complete 
3fe74ac8fbcb: Pull complete 
1159490e84ad: Pull complete 
5d634f471ed7: Pull complete 
c295bfd0a785: Pull complete 
10f607ed1d13: Pull complete 
Digest: sha256:77a89ad001f8f1fd44ed8588abe745e9dbd39682446e378db4cf2aacee1a2596
Status: Downloaded newer image for rancher/agent:v0.9.2
a10e2e7ba664d9636913e8c84e125d6b3d291e1133c1cf1195669db6f1547b64
```

After a few minutes, the new host appears on rancher server interface :
![host-rancher-node-1](https://cloud.githubusercontent.com/assets/4289595/13880360/2b22d5d2-ed1c-11e5-8c45-3c7319ca7913.png)

Now, launch glusterfs stack : 
![host-container-blocked-networking](https://cloud.githubusercontent.com/assets/4289595/13881812/c9395740-ed22-11e5-83c1-83bc18aedeb3.png)

=> blocked on networking because charon failed :

```
rancher-node-1$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                          NAMES
96683937fd7c        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   35 minutes ago      Up 35 minutes       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   42c11a0c-8ae4-4ef7-b039-b9bfe259d998
9793fed4178e        rancher/agent:v0.9.2            "/run.sh run"            About an hour ago   Up About an hour                                                   rancher-agent
```

```
rancher-node-1$ docker exec -it 42c11a0c-8ae4-4ef7-b039-b9bfe259d998 monit status
The Monit daemon 5.6 uptime: 4m 

Process 'rancher-net'
  status                            Does not exist
  monitoring status                 Monitored
  data collected                    Fri, 18 Mar 2016 15:03:30

Process 'rancher-metadata'
  status                            Running
  monitoring status                 Monitored
  pid                               655
  parent pid                        1
  uptime                            36m 
  children                          0
  memory kilobytes                  8032
  memory kilobytes total            8032
  memory percent                    0.1%
  memory percent total              0.1%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Fri, 18 Mar 2016 15:03:30

Process 'rancher-dns'
  status                            Running
  monitoring status                 Monitored
  pid                               646
  parent pid                        1
  uptime                            36m 
  children                          0
  memory kilobytes                  7204
  memory kilobytes total            7204
  memory percent                    0.1%
  memory percent total              0.1%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Fri, 18 Mar 2016 15:03:30

Program 'logrotate'
  status                            Waiting
  monitoring status                 Waiting
  data collected                    Fri, 18 Mar 2016 14:58:57

Process 'haproxy'
  status                            Running
  monitoring status                 Monitored
  pid                               2418
  parent pid                        1
  uptime                            5m 
  children                          0
  memory kilobytes                  3092
  memory kilobytes total            3092
  memory percent                    0.0%
  memory percent total              0.0%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Fri, 18 Mar 2016 15:03:30

Process 'haproxy-monitor'
  status                            Running
  monitoring status                 Monitored
  pid                               830
  parent pid                        1
  uptime                            35m 
  children                          0
  memory kilobytes                  12892
  memory kilobytes total            12892
  memory percent                    0.3%
  memory percent total              0.3%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Fri, 18 Mar 2016 15:03:30

Process 'charon'
  status                            Execution failed
  monitoring status                 Monitored
  data collected                    Fri, 18 Mar 2016 15:03:22

System '96683937fd7c'
  status                            Running
  monitoring status                 Monitored
  load average                      [0.10] [0.14] [0.11]
  cpu                               1.6%us 0.9%sy 0.0%wa
  memory usage                      454672 kB [11.2%]
  swap usage                        0 kB [0.0%]
  data collected                    Fri, 18 Mar 2016 15:03:22
```

```
rancher-node-1$ docker exec -it 42c11a0c-8ae4-4ef7-b039-b9bfe259d998 cat /var/log/charon.log
Mar 18 15:03:31 00[DMN] Starting IKE charon daemon (strongSwan 5.3.5, Linux 4.4.5-docker-root, x86_64)
Mar 18 15:03:31 00[KNL] unable to create netlink socket
Mar 18 15:03:31 00[NET] installing IKE bypass policy failed
Mar 18 15:03:31 00[NET] installing IKE bypass policy failed
Mar 18 15:03:31 00[NET] enabling UDP decapsulation for IPv6 on port 4500 failed
Mar 18 15:03:31 00[NET] installing IKE bypass policy failed
Mar 18 15:03:31 00[NET] installing IKE bypass policy failed
Mar 18 15:03:31 00[NET] enabling UDP decapsulation for IPv4 on port 4500 failed
Mar 18 15:03:31 00[LIB] feature CUSTOM:libcharon in critical plugin 'charon' has unmet dependency: CUSTOM:kernel-ipsec
Mar 18 15:03:31 00[CFG] loading ca certificates from '/usr/local/etc/ipsec.d/cacerts'
Mar 18 15:03:31 00[LIB] opening directory '/usr/local/etc/ipsec.d/cacerts' failed: No such file or directory
Mar 18 15:03:31 00[CFG]   reading directory failed
Mar 18 15:03:31 00[CFG] loading aa certificates from '/usr/local/etc/ipsec.d/aacerts'
Mar 18 15:03:31 00[LIB] opening directory '/usr/local/etc/ipsec.d/aacerts' failed: No such file or directory
Mar 18 15:03:31 00[CFG]   reading directory failed
Mar 18 15:03:31 00[CFG] loading ocsp signer certificates from '/usr/local/etc/ipsec.d/ocspcerts'
Mar 18 15:03:31 00[LIB] opening directory '/usr/local/etc/ipsec.d/ocspcerts' failed: No such file or directory
Mar 18 15:03:31 00[CFG]   reading directory failed
Mar 18 15:03:31 00[CFG] loading attribute certificates from '/usr/local/etc/ipsec.d/acerts'
Mar 18 15:03:31 00[LIB] opening directory '/usr/local/etc/ipsec.d/acerts' failed: No such file or directory
Mar 18 15:03:31 00[CFG]   reading directory failed
Mar 18 15:03:31 00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
Mar 18 15:03:31 00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory
Mar 18 15:03:31 00[CFG]   reading directory failed
Mar 18 15:03:31 00[CFG] loading secrets from '/usr/local/etc/ipsec.secrets'
Mar 18 15:03:31 00[CFG] opening secrets file '/usr/local/etc/ipsec.secrets' failed: No such file or directory
Mar 18 15:03:31 00[LIB] failed to load 1 critical plugin feature
Mar 18 15:03:31 00[DMN] initialization failed - aborting charon
```

**Comment by ailispaw** [comment] 2016-03-18 15:32
@cedvan Thanks for the information.
It looks hard for me to reproduce it, but I will try. :)
What do I need in /data/infra/data/nginx-proxy/certs? And anything else to test?

My understanding....
There are 3 servers.
1.  a server (ip 192.168.1.10) with Ubuntu server 14.04 and docker v10.1 as rancher-server
  It has 2 containers.
2. DNS Server with bind on Raspberry PI (ip 192.168.1.2)
 It is just for DNS server.
3. Ubuntu server with 3 DockerRoot VMs.
 Each VM has rancher/agent container.

Is this right?

**Comment by cedvan** [comment] 2016-03-18 15:46
> It looks hard for me to reproduce it,

Yes sorry :confused:

> What do I need in /data/infra/data/nginx-proxy/certs?

`/data/infra/data/nginx-proxy/certs` just use to enable HTTPS, ignore this, remove volume and work with HTTP :wink: 

> There are 3 servers.

No, only 2 servers.

> 1. a server (ip 192.168.1.10) with Ubuntu server 14.04 and docker v10.1 as rancher-server
>    It has 2 containers.

Right

> 1. DNS Server with bind on Raspberry PI (ip 192.168.1.2)
>    It is just for DNS server.

Right

> 1. Ubuntu server with 3 DockerRoot VMs.

Wrong : VMs started on Ubuntu server (192.168.1.10)

> Each VM has rancher/agent container.

Right

**Comment by ailispaw** [comment] 2016-03-18 15:50
I see. Thanks. I will try it tomorrow.

**Comment by cedvan** [comment] 2016-03-18 15:50
Thank you very much !

**Comment by ailispaw** [comment] 2016-03-19 09:08
@cedvan I created a simplified version of your test to work it with DockerRoot v1.3.5 on Mac OSX.
https://gist.github.com/ailispaw/0df18eb4c0d5f3cb434e

It looks good for IPSec and charon.

```
[docker@rancher-node-1 ~]$ docker exec -it f1764764-54fc-4aad-ae16-0ac9ced8c540 monit status
The Monit daemon 5.6 uptime: 13m

Process 'rancher-net'
  status                            Running
  monitoring status                 Monitored
  pid                               1018
  parent pid                        1
  uptime                            19m
  children                          0
  memory kilobytes                  8632
  memory kilobytes total            8632
  memory percent                    0.8%
  memory percent total              0.8%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Sat, 19 Mar 2016 07:03:19

Process 'rancher-metadata'
  status                            Running
  monitoring status                 Monitored
  pid                               658
  parent pid                        1
  uptime                            19m
  children                          0
  memory kilobytes                  10008
  memory kilobytes total            10008
  memory percent                    0.9%
  memory percent total              0.9%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Sat, 19 Mar 2016 07:03:19

Process 'rancher-dns'
  status                            Running
  monitoring status                 Monitored
  pid                               649
  parent pid                        1
  uptime                            19m
  children                          0
  memory kilobytes                  3660
  memory kilobytes total            3660
  memory percent                    0.3%
  memory percent total              0.3%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Sat, 19 Mar 2016 07:03:19

Program 'logrotate'
  status                            Waiting
  monitoring status                 Waiting
  data collected                    Sat, 19 Mar 2016 06:50:19

Process 'haproxy'
  status                            Running
  monitoring status                 Monitored
  pid                               5323
  parent pid                        1
  uptime                            13m
  children                          0
  memory kilobytes                  3008
  memory kilobytes total            3008
  memory percent                    0.2%
  memory percent total              0.2%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Sat, 19 Mar 2016 07:03:19

Process 'haproxy-monitor'
  status                            Running
  monitoring status                 Monitored
  pid                               973
  parent pid                        1
  uptime                            19m
  children                          0
  memory kilobytes                  8640
  memory kilobytes total            8640
  memory percent                    0.8%
  memory percent total              0.8%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Sat, 19 Mar 2016 07:03:19

Process 'charon'
  status                            Running
  monitoring status                 Monitored
  pid                               984
  parent pid                        1
  uptime                            19m
  children                          0
  memory kilobytes                  4116
  memory kilobytes total            4116
  memory percent                    0.4%
  memory percent total              0.4%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Sat, 19 Mar 2016 07:03:19

System 'e0adcad39e72'
  status                            Running
  monitoring status                 Monitored
  load average                      [0.04] [0.08] [0.13]
  cpu                               1.0%us 0.4%sy 0.0%wa
  memory usage                      342448 kB [33.4%]
  swap usage                        820 kB [0.0%]
  data collected                    Sat, 19 Mar 2016 07:03:19
```

It still has some errors as below, but it looks working.

```
[docker@rancher-node-1 ~]$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED              STATUS              PORTS                                          NAMES
af5f33e29696        rancher/glusterfs:v0.2.0        "/tini -- glusterd -p"   About a minute ago   Up About a minute                                                  r-glusterfs_glusterfs-server_glusterfs-daemon_3
9e510e16a285        rancher/glusterfs:v0.2.0        "/tini -- /opt/ranche"   About a minute ago   Up About a minute   24007-24008/tcp, 49152/tcp, 24007-24008/udp    r-glusterfs_glusterfs-server_3
d49d9453e875        rancher/glusterfs:v0.2.0        "/tini -- glusterd -p"   About a minute ago   Up About a minute                                                  r-glusterfs_glusterfs-server_glusterfs-daemon_2
0dcc1ddb18e5        rancher/glusterfs:v0.2.0        "/tini -- /opt/ranche"   About a minute ago   Up About a minute   24007-24008/tcp, 49152/tcp, 24007-24008/udp    r-glusterfs_glusterfs-server_2
767747a9247f        rancher/glusterfs:v0.2.0        "/tini -- glusterd -p"   2 minutes ago        Up 2 minutes                                                       r-glusterfs_glusterfs-server_glusterfs-daemon_1
7a63782fb6c3        rancher/glusterfs:v0.2.0        "/tini -- /opt/ranche"   2 minutes ago        Up 2 minutes        24007-24008/tcp, 49152/tcp, 24007-24008/udp    r-glusterfs_glusterfs-server_1
821a68c54449        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   6 minutes ago        Up 6 minutes        0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   04230d28-9cd5-449e-a1ed-76e5b6e213f5
6be60c40ad09        rancher/agent:v0.9.2            "/run.sh run"            7 minutes ago        Up 7 minutes                                                       rancher-agent
```

```
[docker@rancher-node-1 ~]$ docker exec -it f1764764-54fc-4aad-ae16-0ac9ced8c540 cat /var/log/charon.log
Mar 19 06:43:57 00[DMN] Starting IKE charon daemon (strongSwan 5.3.5, Linux 4.4.6-docker-root, x86_64)
Mar 19 06:43:57 00[CFG] loading ca certificates from '/usr/local/etc/ipsec.d/cacerts'
Mar 19 06:43:57 00[LIB] opening directory '/usr/local/etc/ipsec.d/cacerts' failed: No such file or directory
Mar 19 06:43:57 00[CFG]   reading directory failed
Mar 19 06:43:57 00[CFG] loading aa certificates from '/usr/local/etc/ipsec.d/aacerts'
Mar 19 06:43:57 00[LIB] opening directory '/usr/local/etc/ipsec.d/aacerts' failed: No such file or directory
Mar 19 06:43:57 00[CFG]   reading directory failed
Mar 19 06:43:57 00[CFG] loading ocsp signer certificates from '/usr/local/etc/ipsec.d/ocspcerts'
Mar 19 06:43:57 00[LIB] opening directory '/usr/local/etc/ipsec.d/ocspcerts' failed: No such file or directory
Mar 19 06:43:57 00[CFG]   reading directory failed
Mar 19 06:43:57 00[CFG] loading attribute certificates from '/usr/local/etc/ipsec.d/acerts'
Mar 19 06:43:57 00[LIB] opening directory '/usr/local/etc/ipsec.d/acerts' failed: No such file or directory
Mar 19 06:43:57 00[CFG]   reading directory failed
Mar 19 06:43:57 00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
Mar 19 06:43:57 00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory
Mar 19 06:43:57 00[CFG]   reading directory failed
Mar 19 06:43:57 00[CFG] loading secrets from '/usr/local/etc/ipsec.secrets'
Mar 19 06:43:57 00[CFG] opening secrets file '/usr/local/etc/ipsec.secrets' failed: No such file or directory
Mar 19 06:43:57 00[LIB] loaded plugins: charon aesni aes des rc2 sha1 sha2 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp xcbc cmac hmac gcm attr kernel-netlink resolve socket-default stroke vici updown xauth-generic
Mar 19 06:43:57 00[JOB] spawning 16 worker threads
Mar 19 06:44:03 13[CFG] loaded IKE shared key for: '%any'
Mar 19 06:44:03 02[CFG] loaded IKE shared key for: '172.18.1.2'
```

![a693b40d-e564-4785-9316-9df1f1a93e36](https://cloud.githubusercontent.com/assets/10327896/13897929/b0bcc3da-ee05-11e5-9942-c14e4f701466.png)

**Comment by cedvan** [comment] 2016-03-20 03:05
Great ! Works with v1.3.5 :smiley:

**Comment by cedvan** [comment] 2016-03-20 03:08
Convoy glusterfs don't works, mount failed. I do not know from where come the problem... Glusterfs provide by rancher must be bad ! :disappointed:

**Comment by ailispaw** [comment] 2016-03-20 04:48
Closing.

**Closed as completed by ailispaw** 2016-03-20 04:48 UTC
Labels: enhancement

**Comment by cedvan** [comment] 2016-03-21 00:32
Ok, the problem came from a difference between versions of glusterfs-server and glusterfs-client. Solved :wink: !

Thank you very much for your work !

**Comment by ailispaw** [comment] 2016-03-21 00:56
@cedvan Nice!!
Thank you for letting me know that.

**Comment by ailispaw** [comment] 2016-03-21 00:58
@cedvan
BTW, do you solve the problem about permissions at a mount folder in a container with glusterfs?

**Comment by cedvan** [comment] 2016-03-21 01:03
Yes !! Containers `mariadb` and `mongodb` works like a charm :smile: !

**Comment by cedvan** [comment] 2016-03-21 01:06
I'm happy :stuck_out_tongue: !

NB : Don't use glusterfs provide by rancher catalog, some bugs persist (I'll try to analyze it to finish the test completely). I've launch and configure glusterfs-server on my ubuntu server to communicate with rancher convoy-gluster :wink:
